version: '3.9'
services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: dhatree_user_service
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
    ports:
      - "${USERSERVICE_PORT}:8080"
